sudo: false
language: python
matrix:
  include:
    # all supported Python versions
    - python: 2.6
      env:
        - TESTDOCSEXAMPLES=1
    - python: 2.7
      env:
        - TESTDOCSEXAMPLES=1
    - python: 2.7
      env:
        - USEPY=3.1
        - TESTDOCSEXAMPLES=1
    - python: 3.2
      env:
        - TESTDOCSEXAMPLES=1
    - python: 3.3
      env:
        - TESTDOCSEXAMPLES=1
    - python: 3.4
      env:
        - TESTDOCSEXAMPLES=1
    - python: 3.5
      env:
        - TESTDOCSEXAMPLES=1
    
    # minimum libcurl we support
    - python: 2.7
      env:
        - USECURL=7.19.0-gssapi
        - USESSL=openssl
        - TESTDOCSEXAMPLES=1
    
    # latest libcurl with each supported SSL backend
    - python: 2.7
      env:
        - USECURL=7.45.0-gssapi
        - USESSL=openssl
        - TESTDOCSEXAMPLES=1
    - python: 2.7
      env:
        - USECURL=7.45.0-gssapi
        - USESSL=libressl
        - USELIBRESSL=2.2.0
    - python: 2.7
      env:
        # libcurl 7.45.0 does not build against gnutls in travis/ubuntu 12.04
        - USECURL=7.44.0-gssapi
        - USESSL=gnutls
    - python: 2.7
      env:
        - USECURL=7.45.0-gssapi
        - USESSL=nss
    - python: 2.7
      env:
        # this configuration should be without gssapi
        - USECURL=7.45.0
        - USESSL=none
    
    # AVOIDSTDIO tested on one Python version, must be Python 2.x
    - python: 2.7
      env:
        - AVOIDSTDIO=yes
    
    # common distributions:
    # CentOS 6
    - python: 2.6
      env:
        - USECURL=7.19.7-gssapi
        - USESSL=openssl
        - USEOPENSSL=1.0.1e
    # Debian Wheezy
    - python: 2.7
      env:
        - USECURL=7.26.0-gssapi
        - USESSL=gnutls
    # Debian Jessie
    - python: 3.4
      env:
        - USECURL=7.38.0-gssapi
        - USESSL=gnutls
install: >
  ./tests/travis/setup.sh
before_script: >
  ./tests/travis/hack.sh
script: >
  ./tests/travis/run.sh
